"""schedules add is_continuous

Revision ID: 27c4325f4677
Revises: f1b3298889eb
Create Date: 2025-03-17 13:38:31.416131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c4325f4677'
down_revision: Union[str, None] = 'f1b3298889eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('is_continuous', sa.Boolean(), nullable=False))
    op.alter_column('schedules', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('schedules', 'is_continuous')
    # ### end Alembic commands ###
